In [3]:
import pyccl as ccl
import numpy as np

In [4]:
rels_Ez  = np.array([1.3, 1.1, 1.5, 
           1.5, 2.0, 2.3, 
           2.6, 3.4, 8.9])

In [5]:
params = {'h': 0.782,  #0.67
        'Omega_cdm': 0.231, #0.272, #0.27
        'Omega_b': 0.0222, #0.045,
        'n_s': 0.815, #0.96
        'Omega_Lambda': 0,
        'w0_fld': -0.969, # -1
        'wa_fld': -0.979} # 0}



In [6]:
#cosmo_ccl = ccl.Cosmology(param_dict)
classy = ccl.boltzmann.classy.Class()
classy.set(params)
classy.compute()

In [7]:
z_arr = np.array([0.07, 0.2, 0.35, 
                  0.6, 0.8, 1.0,
                  1.3, 1.7, 2.5])

In [8]:
Ez_arr = np.array([])
for z in z_arr: 
            Ez = classy.Hubble(z)/classy.Hubble(0)
            Ez_arr = np.append(Ez_arr, Ez) 
Ez_arr

array([1.02800416, 1.07844459, 1.14204031, 1.27581895, 1.41246931,
       1.57427429, 1.85746737, 2.2954017 , 3.32246471])

In [11]:
sig_Ez = rels_Ez*Ez_arr/100
sig_Ez

array([0.01336405, 0.01186289, 0.0171306 , 0.01913728, 0.02824939,
       0.03620831, 0.04829415, 0.07804366, 0.29569936])

In [12]:
cov = np.zeros([len(z_arr), len(z_arr)])

In [13]:
for i in np.arange(len(z_arr)):
    cov[i,i] = sig_Ez[i]**2
    
cov

array([[0.0001786 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.00014073, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.00029346, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.00036624, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.00079803,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00131104, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00233233, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00609081, 0.        ],


In [14]:
np.savetxt('data.txt', Ez_arr)
np.savetxt('cov_mat.txt', cov)